

COLUMNS_IN_TABLE = {
    'artists':[
        'id',
        'name'
    ],
    'artists_details':[
        'id',
        'name',
        'followers',
        'popularity',
        'image_url'
    ],
    'albums':[
        'id',
        'title',
        'album_type',
        'total_tracks',
        'image_url',
        'release_date',
        'release_date_precision'
    ],
    'tracks':[
        'id',
        'title',
        'duration_ms',
        'popularity',
        'disc_number',
        'track_number'
    ],
    'tracks_audio_features':[
        'danceability',
        'energy',
        'instrumentalness',
        'liveness',
        'loudness',
        'speechiness',
        'valence',
        'key',
        'mode',
        'tempo',
        'time_signature'
    ],
    'artists_albums':[
        'artist_id',
        'album_id'
    ],
    'albums_tracks':[
        'album_id',
        'track_id'
    ],
    'tracks_artists':[
        'track_id',
        'artist_id'
    ],
    'playlists':[
        'id',
        'description',
        'followers',
        'image_url',
        'name',
        'owner'
    ],
    'playlists_tracks':[
        'playlist_id',
        'track_id'
    ]
}